#hello deployment.yaml
apiVersion: apps/v1
kingd: Deployment
metadata: 
  name: python-app
  namespace: tiacourse
spec:
  replica: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: python-app
    template:
      metadata:
        labels:
          app: python-app
      spec:
        containers:
        - name: python-app
          image:
          ports:
          - containerPort: 2024

---

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: tiacourse
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: 3000
    targetPort: 80080
    nodePort: 30000